sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

notifications:
  email: false

install:
  - composer install --dev --no-interaction
script:
  - phpunit --configuration Tests/phpunit.xml
after_script:
  - ./.codeclimate.sh
